package test.io;

import java.io.IOException;
import java.io.OutputStream;
import java.net.Socket;

/**
 * Created by Vitalii Zinchenko
 */
public class SocketClientTest {
    public static void main(String[] args) throws IOException, InterruptedException {
        Socket socket = new Socket("localhost", 8181);
        OutputStream stream = socket.getOutputStream();
        String v1 = "WWW";

        System.out.println(v1.getBytes().length);

        stream.write(v1.getBytes());


//        System.out.println(s.getBytes().length);

        int size = 100_000_000;

        byte[] data = new byte[size];

        for (int i = 0; i < size; i++) {
            data[i] = 'Q';
        }

        System.out.println("Writing...");
        stream.write(data);
        System.out.println("Wrote!");


//
//        String s = "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//          "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx" +
//                "qqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxxqqqqqwxxxxxx";

//        String s = "aaaaaa";




        Thread.sleep(1000000000);
    }
}
